/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/impetus/generate-intervention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate AI intervention action
         * @description Calls LLM to decide intervention action based on writing context and mode.
         *
         *     **Request Flow**:
         *     1. Client sends context (last 3 sentences for Muse, full doc for Loki)
         *     2. Backend calls LLM with structured prompt
         *     3. LLM returns typed response (Instructor + Pydantic validation)
         *     4. Backend returns InterventionResponse
         *
         *     **Idempotency**:
         *     - Requests with same `Idempotency-Key` within 15s return cached response
         *     - Prevents duplicate injections on network retry
         *
         *     **Safety Guards**:
         *     - If doc length <50 chars → Backend rejects "delete", returns "provoke" instead
         *     - If anchor out of bounds → 400 Bad Request
         */
        post: operations["generateIntervention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create task with initial content and locks
         * @description Creates a task record storing the current Markdown and lock IDs.
         *     Used by the editor to persist adversarial constraints across sessions.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        /** Get task by ID */
        get: operations["getTask"];
        /** Update task content and locks (optimistic locking) */
        put: operations["updateTask"];
        post?: never;
        /** Delete task and its intervention history */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        /** List intervention actions for a task (most recent first) */
        get: operations["listTaskActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InterventionRequest: {
            /**
             * @description Writing context for LLM decision-making.
             *     - **Muse mode**: Last 3 sentences before cursor
             *     - **Loki mode**: Full document or last 10 sentences (whichever shorter)
             * @example 他打开门,犹豫着要不要进去。
             */
            context: string;
            /**
             * @description Agent working mode:
             *     - **muse**: STUCK-triggered, provoke only
             *     - **loki**: Random-triggered, provoke OR delete
             * @example muse
             * @enum {string}
             */
            mode: "muse" | "loki";
            client_meta: {
                /**
                 * @description Document version counter (increments on each edit)
                 * @example 42
                 */
                doc_version: number;
                /**
                 * @description Cursor position or selection start (ProseMirror absolute position)
                 * @example 1234
                 */
                selection_from: number;
                /**
                 * @description Selection end (same as from if no selection)
                 * @example 1234
                 */
                selection_to: number;
            };
        };
        InterventionResponse: {
            /**
             * @description Intervention action type:
             *     - **provoke**: Inject content with lock_id (un-deletable)
             *     - **delete**: Remove text at anchor position (irreversible)
             *     - **rewrite**: Replace an anchor range with locked content
             * @example provoke
             * @enum {string}
             */
            action: "provoke" | "delete" | "rewrite";
            /**
             * @description Plain text snippet rendered as Markdown (blockquote for provoke, inline for rewrite).
             *     No `[AI施压]` prefixes; UI handles vibe styling.
             * @example 门后是一堵砖墙。
             */
            content?: string | null;
            /**
             * @description Unique lock identifier (ONLY for "provoke" action).
             *     Format: `lock_{ulid}` (sortable UUID alternative)
             * @example lock_01j4z3m8a6q3qz2x8j4z3m8a
             */
            lock_id?: string | null;
            /**
             * @description Target location for action.
             *     - **provoke**: Optional, defaults to cursor position
             *     - **delete**: Required
             */
            anchor?: components["schemas"]["Anchor"];
            /**
             * Format: uuid
             * @description Unique action identifier (UUID v4)
             * @example act_550e8400-e29b-41d4-a716-446655440000
             */
            action_id: string;
        };
        TaskCreateRequest: {
            /** @description Initial task content (Markdown) */
            content: string;
            /**
             * @description Lock IDs present in the content
             * @default []
             * @example [
             *       "lock_01j4z3m8a6q3qz2x8j4z3m8a"
             *     ]
             */
            lock_ids: string[];
        };
        TaskUpdateRequest: {
            /** @description Updated Markdown content */
            content: string;
            /** @description Updated lock IDs extracted from content */
            lock_ids: string[];
            /** @description Expected current version for optimistic locking */
            version: number;
        };
        TaskResponse: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @description Task content (Markdown) */
            content: string;
            /** @description Lock IDs present in the content */
            lock_ids: string[];
            /**
             * Format: date-time
             * @example 2025-01-15T10:30:45.123Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2025-01-15T10:31:45.123Z
             */
            updated_at: string;
            /**
             * @description Optimistic lock version
             * @example 1
             */
            version: number;
        };
        InterventionActionResponse: {
            /**
             * Format: uuid
             * @example 7c4a3c5c-2fb7-41cb-8f6c-7d7b9d77a111
             */
            id: string;
            /** Format: uuid */
            task_id: string;
            /** @enum {string} */
            action_type: "provoke" | "delete" | "rewrite";
            /** @description Stable client-facing action identifier */
            action_id: string;
            /** @description Present for provoke/rewrite actions */
            lock_id?: string | null;
            /** @description Present for provoke/rewrite actions */
            content?: string | null;
            anchor: components["schemas"]["Anchor"];
            /** @enum {string} */
            mode: "muse" | "loki";
            /** @description Author context captured when the action was generated */
            context: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            created_at: string;
        };
        InterventionHistoryResponse: {
            total: number;
            limit: number;
            offset: number;
            actions: components["schemas"]["InterventionActionResponse"][];
        };
        Anchor: components["schemas"]["AnchorPos"] | components["schemas"]["AnchorRange"] | components["schemas"]["AnchorLockId"];
        AnchorPos: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pos";
            /**
             * @description ProseMirror absolute position (0-indexed)
             * @example 1234
             */
            from: number;
        };
        AnchorRange: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "range";
            /**
             * @description Start position (inclusive)
             * @example 1289
             */
            from: number;
            /**
             * @description End position (exclusive)
             * @example 1310
             */
            to: number;
        };
        AnchorLockId: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "lock_id";
            /**
             * @description Reference to existing lock_id to delete
             * @example lock_01j4z3m8a6q3qz2x8j4z3m8a
             */
            ref_lock_id: string;
        };
        ErrorResponse: {
            /**
             * @description Error code (PascalCase)
             * @example ValidationError
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Request body validation failed
             */
            message: string;
            /** @description Additional error context (structure varies by error type) */
            details?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateIntervention: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID v4 to prevent duplicate interventions on retry */
                "Idempotency-Key": string;
                /** @description API contract version (MUST be "2.0.0") */
                "X-Contract-Version": "2.0.0";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionRequest"];
            };
        };
        responses: {
            /** @description Success - intervention action generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionResponse"];
                };
            };
            /** @description Bad Request - invalid anchor position */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "BadRequest",
                     *       "message": "Anchor position out of bounds: from=9999 exceeds document length 1500",
                     *       "details": {
                     *         "anchor": {
                     *           "type": "pos",
                     *           "from": 9999
                     *         },
                     *         "doc_length": 1500
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity - request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "ValidationError",
                     *       "message": "Request body validation failed",
                     *       "details": [
                     *         {
                     *           "field": "mode",
                     *           "message": "must be one of: muse, loki",
                     *           "received": "chaos"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests - rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "RateLimitExceeded",
                     *       "message": "Maximum 10 requests per minute exceeded",
                     *       "details": {
                     *         "limit": 10,
                     *         "window": "60s",
                     *         "retry_after": 42
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error - LLM or backend failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "InternalServerError",
                     *       "message": "LLM service unavailable",
                     *       "details": {
                     *         "llm_provider": "openai",
                     *         "error_code": "503"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation error (content too short/long) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdateRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version conflict (optimistic locking failed) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTaskActions: {
        parameters: {
            query?: {
                /** @example 50 */
                limit?: number;
                /** @example 0 */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Task identifier (UUID v4) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionHistoryResponse"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
