"""Add styles table for user writing style storage

Revision ID: c4a5e8d9f2b1
Revises: fb9f80851e60
Create Date: 2026-02-26 19:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a5e8d9f2b1'
down_revision: Union[str, None] = 'fb9f80851e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('style_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('samples_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_styles_created_at', 'styles', ['created_at'], unique=False)
    op.create_index('idx_styles_updated_at', 'styles', ['updated_at'], unique=False)
    op.create_index('idx_styles_user_id', 'styles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_styles_user_id', table_name='styles')
    op.drop_index('idx_styles_updated_at', table_name='styles')
    op.drop_index('idx_styles_created_at', table_name='styles')
    op.drop_table('styles')
    # ### end Alembic commands ###
