"""Initial migration: tasks and intervention_actions tables

Revision ID: fb9f80851e60
Revises: 
Create Date: 2025-11-08 10:09:57.479157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9f80851e60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lock_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(content) > 0', name='tasks_content_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_table('intervention_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('action_id', sa.String(length=100), nullable=False),
    sa.Column('lock_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('anchor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(action_type = 'provoke' AND content IS NOT NULL AND lock_id IS NOT NULL) OR (action_type = 'delete')", name='actions_provoke_has_content'),
    sa.CheckConstraint("action_type IN ('provoke', 'delete')", name='actions_type_check'),
    sa.CheckConstraint("mode IN ('muse', 'loki')", name='actions_mode_check'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_index('idx_actions_action_id', 'intervention_actions', ['action_id'], unique=False)
    op.create_index('idx_actions_issued_at', 'intervention_actions', ['issued_at'], unique=False)
    op.create_index('idx_actions_mode', 'intervention_actions', ['mode'], unique=False)
    op.create_index('idx_actions_task_id', 'intervention_actions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_actions_task_id', table_name='intervention_actions')
    op.drop_index('idx_actions_mode', table_name='intervention_actions')
    op.drop_index('idx_actions_issued_at', table_name='intervention_actions')
    op.drop_index('idx_actions_action_id', table_name='intervention_actions')
    op.drop_table('intervention_actions')
    op.drop_index('idx_tasks_updated_at', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
